title: "Ben Nazer Research"
description: "Work-in-progress notes on EAP research projects"
remote_theme: "mmistakes/minimal-mistakes"
url: "https://bensresearch.space"
author: "Ben"
markdown: kramdown
plugins:
  - jekyll-include-cache

header_pages: 
  - about.md
